//
// Created by tiago on 19/12/2025.
//

#ifndef PROJETO_ALGORITMOS_E_ESTRUTURAS_DE_DADOS_R2_4_BINARY_FILES_H
#define PROJETO_ALGORITMOS_E_ESTRUTURAS_DE_DADOS_R2_4_BINARY_FILES_H
#include "r2_3_text_files.h"




void test_r2_r4();
#endif //PROJETO_ALGORITMOS_E_ESTRUTURAS_DE_DADOS_R2_4_BINARY_FILES_H