#ifndef PROJETO_ALGORITMOS_E_ESTRUTURAS_DE_DADOS_R1_5_TERM_FREQUENCY_H
#define PROJETO_ALGORITMOS_E_ESTRUTURAS_DE_DADOS_R1_5_TERM_FREQUENCY_H

/**
 * @brief funçao de teste para o requisito R1.5
 */
void test_r1_5();

#endif //PROJETO_ALGORITMOS_E_ESTRUTURAS_DE_DADOS_R1_5_TERM_FREQUENCY_H